### ISSUE TITLE
Extending/dragging a note out of bounds

### ISSUE THREAD

**Issue by Stephen-ONeil** [GarvinH/StickyNotes#2]
Either vertically or horizontally, you can click and drag a sticky out of the initial bounds of the screen and end up in a white void. Can think of a couple different approaches for improving on that, but I'll leave the design brainstorming up to you, at least initially! 

Feel free to comment some ideas here if you want to do back and forth on them, or just take your first one and run with it as a new branch/PR addressing this issue.

**Comment by GarvinH** [comment]
Fixed as of [9dc6c99](https://github.com/GarvinH/StickyNotes/commit/9dc6c998c6803803b5870780ae39c9639c0fe8b5).
Thanks!
